### ISSUE TITLE
Bring back deleted sections from README

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/robotframework-plugin#4]
Commit https://github.com/kiwitcms/robotframework-plugin/commit/dcc11bd0dcd240dc006dd393f3c4f51164d32ceb removed some sections from the README file. 

After we're done with polishing up this package for release I need to go back to this and figure out what information is still relevant and add it back.

**Comment by shadeimi** [comment]
ok, i'll check it too, because our documentation is too poor
